package: myevents
version: '2.2.2'
author: Joachim Wendenburg
supportpage: www.github.com/wende60/myevents

page:
    title: 'MyEvents'
    perm: myevents[]
    subpages:
        event_list: { title: 'MyEvents Event Liste' }
        event_add: { title: 'MyEvents Neuer Event' }
        event_help: { title: 'MyEvents Hilfe' }

requires:
    redaxo: '~5.1'
    packages:
        markitup: '^3.0.0'
